name: rider_pay_driver
description: "A new Flutter project."

publish_to: 'none'

version: 1.3.5+7

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_riverpod: ^3.0.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  pinput: ^5.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  dio: ^5.9.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  url_launcher: ^6.3.2
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  flutter_local_notifications: ^19.4.2
  flutter_cashfree_pg_sdk: ^2.2.9+47
  just_audio: ^0.10.5
  vibration: ^3.1.4
  connectivity_plus: ^7.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
  assets:
    - assets/
    - assets/icon/
    - assets/fonts/
    - assets/sound/
    - assets/images/



#run 3.35 version
#  storePassword=12345678
#  keyPassword=12345678
#  keyAlias=riderpay_driver
#  storeFile=D:/jks/rider_pay_driver.jks
